### ISSUE TITLE
On a playlist, when we change the task type of a preview, the comment section doesn't update to the new task type

### ISSUE THREAD

**Issue by gwendupre** [cgwire/kitsu#545]
on a tv show, short, feature film.

On a playlist (from the playlist module, or playlist on the fly), If we change the task type of the preview, the preview will update, but not the comment section.

**Comment by frankrousseau** [comment]
It should be fixed. Can you try again?

**Comment by gwendupre** [comment]
it's fixed when you manually change the task type, but not with the batch change task type button.

**Comment by frankrousseau** [comment]
I cannot reproduce the batch change bug. Can you try again?

**Comment by gwendupre** [comment]
i still have the issue

![image](https://user-images.githubusercontent.com/42962633/100869383-46f67980-349d-11eb-92fe-0b31a15897e9.png)

**Comment by frankrousseau** [comment]
It seems to be fixed. Can you try again?

**Comment by gwendupre** [comment]
It's fixed, thanks
